server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location /catalog/ { proxy_pass http://catalog-service:8080/; }
  location /orders/ { proxy_pass http://order-service:8081/; }
  location /insights/ { proxy_pass http://insights-service:8082/; }
  location / { try_files $uri $uri/ /index.html; }
}
